[project]
name = 'Property-Technology-Integration-Contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.iot-device-coordination]
path = 'contracts/iot-device-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.smart-building-management]
path = 'contracts/smart-building-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
